# -*- coding: utf-8 -*-

{
    "name": "Qualimaster",
    "version": "0.0.019",
    "author": "Alexandre Defendi",
    "category": "Account",
    "website": "http://www.evoluirinformatica.com.br",
    "description": "",
    'depends': ['l10n_br_account',
                'hr',
                'crm',
                'project',
                ],
    'js': [],
    'init_xml': [],
    'update_xml': [
        'qualimaster_view.xml',
        'hr_view.xml',
        'account_invoice_view.xml',
        'product_view.xml',
        'res_company_view.xml',
        'sale_view.xml',
        'analytic_view.xml',
        'project_view.xml',
        'crm_lead_view.xml',
        'account_view.xml',
        ],
    'demo_xml': [],
    'test': [],
    'installable': True,
    'active': False,
}
